// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createInput = `-- name: CreateInput :one
INSERT INTO inputs (id, name, format) VALUES ($1, $2, $3) RETURNING id, name, format
`

type CreateInputParams struct {
	ID     uuid.UUID
	Name   string
	Format string
}

func (q *Queries) CreateInput(ctx context.Context, arg CreateInputParams) (Input, error) {
	row := q.db.QueryRow(ctx, createInput, arg.ID, arg.Name, arg.Format)
	var i Input
	err := row.Scan(&i.ID, &i.Name, &i.Format)
	return i, err
}
